- id: '1770049377863'
  alias: Outdoor Lights
  description: Off at sunrise, on at sunset
  triggers:
  - trigger: sun
    event: sunrise
    offset: 0
    id: sunrise
  - trigger: sun
    event: sunset
    offset: 0
    id: sunset
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - sunrise
      sequence:
      - type: turn_off
        device_id: 4f23273174b160f318402fc3f28553d0
        entity_id: 16969815276aabd09f58ead9a9ff790a
        domain: light
      - type: turn_off
        device_id: c2a96afff65a527b5f5a694521ad7860
        entity_id: 3352756a43d9d36fcea17838055ad2d6
        domain: switch
    - conditions:
      - condition: trigger
        id:
        - sunset
      sequence:
      - type: turn_on
        device_id: 4f23273174b160f318402fc3f28553d0
        entity_id: 16969815276aabd09f58ead9a9ff790a
        domain: light
      - type: turn_on
        device_id: c2a96afff65a527b5f5a694521ad7860
        entity_id: 3352756a43d9d36fcea17838055ad2d6
        domain: switch
  mode: single
- id: '1770925409444'
  alias: Kitchen Light Switch
  description: Toggle kitchen lights from wall switch
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.shelly_1pm_mini_gen3_input_0
  conditions: []
  actions:
  - action: light.toggle
    metadata: {}
    target:
      entity_id: light.keuken_lampen
    data:
      transition: 3
  mode: single
- id: '1770926325987'
  alias: Schakelaar Aanrecht
  description: ''
  triggers:
  - type: not_powered
    device_id: fb1b0617f23199a754ae21eda9d530bd
    entity_id: 0a475fda8d16765564075948373fcdae
    domain: binary_sensor
    trigger: device
  - type: powered
    device_id: fb1b0617f23199a754ae21eda9d530bd
    entity_id: 0a475fda8d16765564075948373fcdae
    domain: binary_sensor
    trigger: device
  conditions: []
  actions:
  - action: light.toggle
    metadata: {}
    target:
      entity_id:
      - light.signify_netherlands_b_v_ltv001
      - light.aanrecht_3_white_ambiance
      - light.aanrecht_1_white_ambiance
    data:
      transition: 3
  mode: single
- id: '1771083115129'
  alias: Toilet Light
  description: On when occupied, off when clear
  triggers:
  - trigger: occupancy.detected
    target:
      entity_id: binary_sensor.radar_toilet_presence
    options:
      behavior: each
      for: 00:00:00
    id: 'On'
  - trigger: occupancy.cleared
    target:
      entity_id: binary_sensor.radar_toilet_presence
    options:
      behavior: each
      for: 00:00:10
    id: 'Off'
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - 'On'
      sequence:
      - type: turn_on
        device_id: 180c9996462414e54ad71e5803c912e6
        entity_id: 33f5406ab1cfed5c6b4a1334ed770cc9
        domain: light
    - conditions:
      - condition: trigger
        id:
        - 'Off'
      sequence:
      - type: turn_off
        device_id: 180c9996462414e54ad71e5803c912e6
        entity_id: 33f5406ab1cfed5c6b4a1334ed770cc9
        domain: light
  mode: single
- id: '1771598748493'
  alias: Back Entrance Light
  description: On when occupied, off when clear
  triggers:
  - type: occupied
    device_id: 9b1f5e52acca78d5befbdc6dba721b40
    entity_id: 7d9ce28b74f15aedcc8a55552afdd976
    domain: binary_sensor
    metadata:
      secondary: false
    trigger: device
    id: 'On'
  - type: not_occupied
    device_id: 9b1f5e52acca78d5befbdc6dba721b40
    entity_id: 7d9ce28b74f15aedcc8a55552afdd976
    domain: binary_sensor
    trigger: device
    id: 'Off'
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - 'On'
      sequence:
      - type: turn_on
        device_id: 4507af437e2d2fe2e5e961b4c7270d62
        entity_id: c11ced3fb72f5c5f8d2757c52189e2f7
        domain: light
    - conditions:
      - condition: trigger
        id:
        - 'Off'
      sequence:
      - type: turn_off
        device_id: 4507af437e2d2fe2e5e961b4c7270d62
        entity_id: c11ced3fb72f5c5f8d2757c52189e2f7
        domain: light
  mode: single
- id: '1771602575085'
  alias: Front Entrance Light
  description: On when occupied, off when clear
  triggers:
  - type: occupied
    device_id: ad9a71ee5179cd0de2f029a1f383c4d3
    entity_id: c078d0f69f58aa0a15e0060a5bbe86fb
    domain: binary_sensor
    metadata:
      secondary: false
    trigger: device
    id: 'On'
  - type: not_occupied
    device_id: ad9a71ee5179cd0de2f029a1f383c4d3
    entity_id: c078d0f69f58aa0a15e0060a5bbe86fb
    domain: binary_sensor
    trigger: device
    id: 'Off'
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - 'On'
      sequence:
      - type: turn_on
        device_id: 35707b7795cc4f2c550b05e89b5a3d41
        entity_id: 4165d06b123d94380c69f8e0240fcb02
        domain: light
    - conditions:
      - condition: trigger
        id:
        - 'Off'
      sequence:
      - type: turn_off
        device_id: 35707b7795cc4f2c550b05e89b5a3d41
        entity_id: 4165d06b123d94380c69f8e0240fcb02
        domain: light
  mode: single
- id: '1771603291635'
  alias: Storage Light
  description: On when occupied, off when clear
  triggers:
  - type: occupied
    device_id: 37aba432335d843ce7fc6257baf6312f
    entity_id: 24ba57b22a3df5663bafbd19360e07b0
    domain: binary_sensor
    metadata:
      secondary: false
    trigger: device
    id: 'On'
  - type: not_occupied
    device_id: 37aba432335d843ce7fc6257baf6312f
    entity_id: 24ba57b22a3df5663bafbd19360e07b0
    domain: binary_sensor
    trigger: device
    id: 'Off'
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - 'On'
      sequence:
      - type: turn_on
        device_id: d6fffd44fb56ee53ba1dc75cdb889ffc
        entity_id: d0a3ef5d8f8440006ef87c135b3527eb
        domain: switch
    - conditions:
      - condition: trigger
        id:
        - 'Off'
      sequence:
      - type: turn_off
        device_id: d6fffd44fb56ee53ba1dc75cdb889ffc
        entity_id: 653e8ae7736540b157b664a72b3090d3
        domain: light
  mode: single
- id: '1771603404642'
  alias: Office Ceiling Light
  description: On when occupied, off when clear
  triggers:
  - trigger: occupancy.detected
    target:
      entity_id: binary_sensor.radar_office_presence
    options:
      behavior: each
      for: 00:00:00
    id: 'On'
  - trigger: occupancy.cleared
    target:
      entity_id: binary_sensor.radar_office_presence
    options:
      behavior: each
      for: 00:00:00
    id: 'Off'
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - 'On'
      sequence:
      - type: turn_on
        device_id: 5a88e64aea84fbb5610579cbf3c258a2
        entity_id: 0b04e66af7aa26ec346b0b8f16378f51
        domain: switch
    - conditions:
      - condition: trigger
        id:
        - 'Off'
      sequence:
      - type: turn_off
        device_id: 5a88e64aea84fbb5610579cbf3c258a2
        entity_id: a5cfdbd90d613746ac1faa2254f38938
        domain: light
  mode: single
- id: '1771775471467'
  alias: Wasmachine klaar bericht
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sensor.wasmachine
    to:
    - program_ended
  conditions: []
  actions:
  - action: notify.mobile_app_iphone_14_pro_stijn
    metadata: {}
    data:
      message: De wasmachine is klaar
      title: Wasmachine
  - action: notify.mobile_app_iphone_van_annelot
    metadata: {}
    data:
      message: De wasmachine is klaar
  mode: single
- id: '1771776247448'
  alias: Droger klaar bericht
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sensor.tumble_dryer
    to:
    - program_ended
  conditions: []
  actions:
  - action: notify.mobile_app_iphone_van_annelot
    metadata: {}
    data:
      message: De droger is klaar
      title: Droger
  - action: notify.mobile_app_iphone_14_pro_stijn
    metadata: {}
    data:
      message: De droger is klaar
      title: Droger
  mode: single
- id: '1771955557375'
  alias: Kitchen Remote
  description: ''
  triggers:
  - device_id: 453241f0b204d7d7848e5683cca12a28
    domain: bthome
    type: button_1
    subtype: press
    trigger: device
    id: Button1
  - device_id: 453241f0b204d7d7848e5683cca12a28
    domain: bthome
    type: button_2
    subtype: press
    trigger: device
    id: Button2
  - device_id: 453241f0b204d7d7848e5683cca12a28
    domain: bthome
    type: button_3
    subtype: press
    trigger: device
    id: Button3
  - device_id: 453241f0b204d7d7848e5683cca12a28
    domain: bthome
    type: button_4
    subtype: press
    trigger: device
    id: Button4
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - Button1
      sequence:
      - action: light.turn_off
        metadata: {}
        target:
          entity_id: light.keuken_lampen
        data: {}
      - action: input_select.select_option
        metadata: {}
        target:
          entity_id: input_select.kitchen_scene
        data:
          option: 'Off'
    - conditions:
      - condition: trigger
        id:
        - Button2
      sequence:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.kitchen_cozy
      - action: input_select.select_option
        metadata: {}
        target:
          entity_id: input_select.kitchen_scene
        data:
          option: Cozy
    - conditions:
      - condition: trigger
        id:
        - Button3
      sequence:
      - action: scene.turn_on
        metadata: {}
        target:
          entity_id: scene.kitchen_warm
        data: {}
      - action: input_select.select_option
        metadata: {}
        target:
          entity_id: input_select.kitchen_scene
        data:
          option: Warm
    - conditions:
      - condition: trigger
        id:
        - Button4
      sequence:
      - action: scene.turn_on
        metadata: {}
        target:
          entity_id: scene.kitchen_white
        data: {}
      - action: input_select.select_option
        metadata: {}
        target:
          entity_id: input_select.kitchen_scene
        data:
          option: White
  mode: single
- id: '1772006878200'
  alias: CO2 Ventilation LED
  description: Red LED and notify when CO2 is high, LED off when OK
  triggers:
  - trigger: numeric_state
    entity_id: sensor.co2_temp_lux_toren_co2
    above: 1200
    id: high
  - trigger: numeric_state
    entity_id: sensor.co2_temp_lux_toren_co2
    below: 1200
    id: ok
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - high
      sequence:
      - action: notify.mobile_app_iphone_14_pro_stijn
        metadata: {}
        data:
          message: Ventileren noodzakelijk Co2 boven 1200 ppm
      - action: light.turn_on
        metadata: {}
        target:
          entity_id: light.co2_temp_lux_toren_rgb_led
        data:
          rgb_color:
          - 241
          - 9
          - 9
    - conditions:
      - condition: trigger
        id:
        - ok
      sequence:
      - action: light.turn_off
        metadata: {}
        target:
          entity_id: light.co2_temp_lux_toren_rgb_led
        data: {}
  mode: single
- id: '1779224453660'
  alias: Living Room Light Switch
  description: Toggle living room lights from wall switch
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.shelly1minig3_dcda0ce3543c_input_0
  conditions: []
  actions:
  - action: light.toggle
    metadata: {}
    target:
      entity_id: light.plafondlamp
    data: {}
  mode: single
- id: '1786798163851'
  alias: Landing Lights
  description: Aan bij aanwezigheid, uit bij vrij
  triggers:
  - trigger: occupancy.detected
    target:
      entity_id: binary_sensor.radar_overloop_presence
    options:
      behavior: each
      for: 00:00:00
    id: 'On'
  - trigger: occupancy.cleared
    target:
      entity_id: binary_sensor.radar_overloop_presence
    options:
      behavior: each
      for: 00:00:00
    id: 'Off'
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - 'On'
      sequence:
      - action: light.turn_on
        metadata: {}
        target:
          area_id: overloop
        data: {}
    - conditions:
      - condition: trigger
        id:
        - 'Off'
      sequence:
      - action: light.turn_off
        metadata: {}
        target:
          area_id: overloop
        data: {}
  mode: single
- id: '1786800910398'
  alias: Bathroom Lights
  description: ''
  triggers:
  - trigger: occupancy.detected
    target:
      entity_id: binary_sensor.radar_badkamer_presence
    options:
      behavior: each
      for: 00:00:00
    id: 'On'
  - trigger: occupancy.cleared
    target:
      entity_id: binary_sensor.radar_badkamer_presence
    options:
      behavior: each
      for: 00:00:00
    id: 'Off'
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - 'On'
      sequence:
      - action: light.turn_on
        metadata: {}
        target:
          device_id: c3fb4e5e99fa0cb63a3f0a1a9c4e8789
        data: {}
    - conditions:
      - condition: trigger
        id:
        - 'Off'
      sequence:
      - action: light.turn_off
        metadata: {}
        target:
          device_id: c3fb4e5e99fa0cb63a3f0a1a9c4e8789
        data: {}
  mode: single
- id: '1786804508836'
  alias: Upstairs Toilet Light
  description: On when occupied, off when clear
  triggers:
  - trigger: occupancy.detected
    target:
      entity_id: binary_sensor.toilet_2_radar_toilet_boven_presence
    options:
      behavior: each
      for: 00:00:00
    id: 'On'
  - trigger: occupancy.cleared
    target:
      entity_id: binary_sensor.toilet_2_radar_toilet_boven_presence
    options:
      behavior: each
      for: 00:00:00
    id: 'Off'
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - 'On'
      sequence:
      - action: light.turn_on
        metadata: {}
        target:
          device_id: 53e1c69d5963fb7f544d234edc727f4c
        data: {}
    - conditions:
      - condition: trigger
        id:
        - 'Off'
      sequence:
      - action: light.turn_off
        metadata: {}
        target:
          device_id: 53e1c69d5963fb7f544d234edc727f4c
        data: {}
  mode: single
- id: '1787777764749'
  alias: Kitchen Shelly Relay Watchdog
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - switch.shelly_1pm_mini_gen3
    to:
    - 'off'
    - unavailable
    - unknown
  conditions: []
  actions:
  - action: switch.turn_on
    metadata: {}
    target:
      entity_id: switch.shelly_1pm_mini_gen3
    data: {}
  mode: single
- id: '1787777886080'
  alias: Kitchen Counter Shelly Relay Watchdog
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - switch.shelly1pmminig3_e4b063f63a84
    to:
    - 'off'
    - unavailable
    - unknown
  conditions: []
  actions:
  - action: switch.turn_on
    metadata: {}
    target:
      entity_id: switch.shelly1pmminig3_e4b063f63a84
    data: {}
  mode: single
- id: '1787778167512'
  alias: Living room Shelly Relay Watchdog
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - switch.shelly1minig3_dcda0ce3543c
    to:
    - 'off'
    - unavailable
    - unknown
  conditions: []
  actions:
  - action: switch.turn_on
    metadata: {}
    target:
      entity_id: switch.shelly1minig3_dcda0ce3543c
    data: {}
  mode: single
- id: '1787779598184'
  alias: Kitchen scene from dropdown
  description: ''
  triggers:
  - trigger: select.selection_changed
    target:
      entity_id: input_select.kitchen_scene
    options: {}
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: select.is_option_selected
        target:
          entity_id: input_select.kitchen_scene
        options:
          behavior: any
          for: 00:00:00
          option:
          - 'Off'
      sequence:
      - action: light.turn_off
        metadata: {}
        target:
          entity_id: light.keuken_lampen
        data: {}
    - conditions:
      - condition: select.is_option_selected
        target:
          entity_id: input_select.kitchen_scene
        options:
          behavior: any
          for: 00:00:00
          option:
          - Cozy
      sequence:
      - action: scene.turn_on
        metadata: {}
        target:
          entity_id: scene.kitchen_cozy
        data: {}
    - conditions:
      - condition: select.is_option_selected
        target:
          entity_id: input_select.kitchen_scene
        options:
          behavior: any
          for: 00:00:00
          option:
          - Warm
      sequence:
      - action: scene.turn_on
        metadata: {}
        target:
          entity_id: scene.kitchen_warm
        data: {}
    - conditions:
      - condition: select.is_option_selected
        target:
          entity_id: input_select.kitchen_scene
        options:
          behavior: any
          for: 00:00:00
          option:
          - White
      sequence:
      - action: scene.turn_on
        metadata: {}
        target:
          entity_id: scene.kitchen_white
        data: {}
  mode: single
- id: '1787780593577'
  alias: Living Room scene from Dropdown
  description: ''
  triggers:
  - trigger: select.selection_changed
    target:
      entity_id: input_select.living_room_scene
    options: {}
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: select.is_option_selected
        target:
          entity_id: input_select.living_room_scene
        options:
          behavior: any
          for: 00:00:00
          option:
          - 'Off'
      sequence:
      - action: light.turn_off
        metadata: {}
        target:
          entity_id: light.woonkamer_toren
        data: {}
    - conditions:
      - condition: select.is_option_selected
        target:
          entity_id: input_select.living_room_scene
        options:
          behavior: any
          for: 00:00:00
          option:
          - Cozy
      sequence:
      - action: scene.turn_on
        metadata: {}
        target:
          entity_id: scene.living_room_cozy
        data: {}
  mode: single
