#!/usr/bin/env python3
"""Build dashboards/radar_combined.yaml from ONE UI-editable Lovelace dashboard.

The template dashboard uses Frontdoor radar entities. The script duplicates each section
for Office, Toilet, Backdoor, and Storage (entity id substitution) and adds input_select visibility so the UI
dropdown still works.

Template storage file (after you create dashboard id `radar_template` in HA):
  .storage/lovelace.radar_template

Output is JSON (valid YAML 1.2) for Home Assistant.
"""

import json
import sys
from pathlib import Path

# Must match options in configuration.yaml (input_select.radar_dashboard_location)
FRONTDOOR_STATE = "Frontdoor"
OFFICE_STATE = "Office"
TOILET_STATE = "Toilet"
BACKDOOR_STATE = "Backdoor"
STORAGE_STATE = "Storage"
SELECT_ENTITY = "input_select.radar_dashboard_location"

# Template must reference the radar entities; other locations are generated by substitution.
FRONTDOOR_ENTITY_INFIX = "radar_frontdoor"
OFFICE_ENTITY_INFIX = "radar_office"
TOILET_ENTITY_INFIX = "radar_toilet"
BACKDOOR_ENTITY_INFIX = "radar_backdoor"
STORAGE_ENTITY_INFIX = "radar_storage"

TEMPLATE_STORAGE = "lovelace.radar_template"


def wrap_card(card, select_state, section_visibility=None):
    card = dict(card)
    vis = list(card.get("visibility") or [])
    if section_visibility:
        vis.extend(section_visibility)
    vis.append({"condition": "state", "entity": SELECT_ENTITY, "state": select_state})
    card["visibility"] = vis
    return card


def merge_section_grids(h_sec, w_sec, selector_card):
    h_vis = h_sec.get("visibility")
    w_vis = w_sec.get("visibility")
    out_cards = []
    if selector_card is not None:
        out_cards.append(selector_card)
    for c in h_sec.get("cards", []):
        out_cards.append(wrap_card(c, HAL_STATE, h_vis))
    for c in w_sec.get("cards", []):
        out_cards.append(wrap_card(c, WERK_STATE, w_vis))
    sec = {"type": "grid", "cards": out_cards}
    for k in ("column_span", "columns"):
        if k in h_sec:
            sec[k] = h_sec[k]
    return sec


def clone_for_location(obj):
    return json.loads(json.dumps(obj).replace(FRONTDOOR_ENTITY_INFIX, OFFICE_ENTITY_INFIX).replace(FRONTDOOR_ENTITY_INFIX, TOILET_ENTITY_INFIX).replace(FRONTDOOR_ENTITY_INFIX, BACKDOOR_ENTITY_INFIX).replace(FRONTDOOR_ENTITY_INFIX, STORAGE_ENTITY_INFIX))


def main():
    root = Path(__file__).resolve().parents[1]
    store = root / ".storage"
    path = store / TEMPLATE_STORAGE
    if not path.is_file():
        print(
            f"Missing {path}\n"
            "In Home Assistant: Settings → Dashboards → Add dashboard → "
            "pick an ID/key `radar_template` (storage mode). "
            "Design the layout with HAL sensor entities, then re-run.",
            file=sys.stderr,
        )
        sys.exit(1)

    raw = json.loads(path.read_text(encoding="utf-8"))
    try:
        view = raw["data"]["config"]["views"][0]
    except (KeyError, IndexError) as e:
        print(f"Unexpected template JSON shape: {e}", file=sys.stderr)
        sys.exit(1)

    sections = view.get("sections") or []
    if not sections:
        print("Template has no sections", file=sys.stderr)
        sys.exit(1)

    selector_card = {
        "type": "entities",
        "title": "Radar",
        "entities": [SELECT_ENTITY],
    }

    new_sections = []
    for i, sec in enumerate(sections):
        h_sec = json.loads(json.dumps(sec))
        w_sec = clone_for_werkkamer(h_sec)
        sel = selector_card if i == 0 else None
        new_sections.append(merge_section_grids(h_sec, w_sec, sel))

    out_view = {
        "type": "sections",
        "max_columns": view.get("max_columns", 4),
        "path": "radar-combined",
        "title": view.get("title", "Radars"),
        "sections": new_sections,
    }

    doc = {"views": [out_view]}
    out = root / "dashboards" / "radar_combined.yaml"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(doc, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {out} from {path.name}")


if __name__ == "__main__":
    main()
