substitutions:
  name: ld2412-c3-6
  friendly_name: LD2412-C3-6

packages:
  esp32-c3-idf: !include Common/esp32-c3.yaml

uart:
  tx_pin: GPIO3
  rx_pin: GPIO4
  baud_rate: 115200
  parity: NONE
  stop_bits: 1
  id: serial

ld2412:
  uart_id: serial
  setup_priority: -100

binary_sensor:
  - platform: ld2412
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
    dynamic_background_correction_status:
      name: Dynamic Background Correction Status

switch:
  - platform: ld2412
    engineering_mode:
      name: Engineering Mode
    bluetooth:
      name: Bluetooth
      restore_mode: ALWAYS_OFF

number:
  - platform: ld2412
    timeout:
      name: timeout
    min_distance_gate:
      name: Minimum Distance Gate
    max_distance_gate:
      name: Maximum Distance Gate
    light_threshold:
      name: Light Threshold
    gate_0:
      move_threshold:
        name: g0_move_threshold
      still_threshold:
        name: g0_still_threshold
    gate_1:
      move_threshold:
        name: g1_move_threshold
      still_threshold:
        name: g1_still_threshold
    gate_2:
      move_threshold:
        name: g2_move_threshold
      still_threshold:
        name: g2_still_threshold
    gate_3:
      move_threshold:
        name: g3_move_threshold
      still_threshold:
        name: g3_still_threshold
    gate_4:
      move_threshold:
        name: g4_move_threshold
      still_threshold:
        name: g4_still_threshold
    gate_5:
      move_threshold:
        name: g5_move_threshold
      still_threshold:
        name: g5_still_threshold
    gate_6:
      move_threshold:
        name: g6_move_threshold
      still_threshold:
        name: g6_still_threshold
    gate_7:
      move_threshold:
        name: g7_move_threshold
      still_threshold:
        name: g7_still_threshold
    gate_8:
      move_threshold:
        name: g8_move_threshold
      still_threshold:
        name: g8_still_threshold
    gate_9:
      move_threshold:
        name: g9_move_threshold
      still_threshold:
        name: g9_still_threshold
    gate_10:
      move_threshold:
        name: g10_move_threshold
      still_threshold:
        name: g10_still_threshold
    gate_11:
      move_threshold:
        name: g11_move_threshold
      still_threshold:
        name: g11_still_threshold
    gate_12:
      move_threshold:
        name: g12_move_threshold
      still_threshold:
        name: g12_still_threshold
    gate_13:
      move_threshold:
        name: g13_move_threshold
      still_threshold:
        name: g13_still_threshold

sensor:
  - platform: ld2412
    moving_distance:
      name : Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance
    light:
        name: light
    gate_0:
      move_energy:
        name: g0_move_energy
      still_energy:
        name: g0_still_energy
    gate_1:
      move_energy:
        name: g1_move_energy
      still_energy:
        name: g1_still_energy
    gate_2:
      move_energy:
        name: g2_move_energy
      still_energy:
        name: g2_still_energy
    gate_3:
      move_energy:
        name: g3_move_energy
      still_energy:
        name: g3_still_energy
    gate_4:
      move_energy:
        name: g4_move_energy
      still_energy:
        name: g4_still_energy
    gate_5:
      move_energy:
        name: g5_move_energy
      still_energy:
        name: g5_still_energy
    gate_6:
      move_energy:
        name: g6_move_energy
      still_energy:
        name: g6_still_energy
    gate_7:
      move_energy:
        name: g7_move_energy
      still_energy:
        name: g7_still_energy
    gate_8:
      move_energy:
        name: g8_move_energy
      still_energy:
        name: g8_still_energy
    gate_9:
      move_energy:
        name: g9_move_energy
      still_energy:
        name: g9_still_energy
    gate_10:
      move_energy:
        name: g10_move_energy
      still_energy:
        name: g10_still_energy
    gate_11:
      move_energy:
        name: g11_move_energy
      still_energy:
        name: g11_still_energy
    gate_12:
      move_energy:
        name: g12_move_energy
      still_energy:
        name: g12_still_energy
    gate_13:
      move_energy:
        name: g13_move_energy
      still_energy:
        name: g13_still_energy

button:
  - platform: ld2412
    factory_reset:
      name: Factory Reset
    restart:
      name: Restart
    query_params:
      name: Query Params
    start_dynamic_background_correction:
      name: Start Dynamic Background Correction

text_sensor:
  - platform: ld2412
    version:
      name: Firmware Version
    mac_address:
      name: Mac Address

select:
  - platform: ld2412
    out_pin_level:
      name: Hardware Output Pin Level
    distance_resolution:
      name: Distance Resolution
    light_function:
      name: Light Function
    baud_rate:
      name: Baud Rate